# TODO: test if MYSQL_ROOT_PASSWORD have to be defined, and be the same on phpmyadmin

version: '3'

services:
  backend-database:
    build:
      context: ./images/backend-database
      args:
        DEFAULT_DATABASE_REPOSITORY: https://github.com/ABAPlan/database-schema.git
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - "${DB_FOLDER}:/var/lib/mysql"

  wordpress-database:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${WP_DB_NAME}
      MYSQL_USER: ${WP_DB_USER}
      MYSQL_PASSWORD: ${WP_DB_PASS}
    volumes:
      - "${WP_DB_FOLDER}:/var/lib/mysql"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.8.1
    environment:
      VIRTUAL_HOST: phpmyadmin.${BASE_URL}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
    depends_on:
      - backend-database
      - wordpress-database
  
  backend-server:
    build:
      context: ./images/backend-server
      args:
        REMOTE_REPOSITORY: https://github.com/ABAPlan/backend.git
    environment:
      VIRTUAL_HOST: backend.${BASE_URL}
      DB_HOSTNAME: database
      DB_DATABASE: ${DB_NAME}
      DB_USERNAME: ${DB_USER}
      DB_PASSWORD: ${DB_PASS}
    depends_on:
      - backend-database
  
  frontend-editor:
    build:
      context: ./images/frontend-editor
      args:
        REMOTE_REPOSITORY: https://github.com/ABAPlan/frontend-editor.git
        BACKEND_URL: backend.${BASE_URL}
    environment:
      VIRTUAL_HOST: editor.${BASE_URL}
    depends_on:
      - backend-server
  
  frontend-reader:
    build:
      context: ./images/frontend-reader
      args:
        REMOTE_REPOSITORY: https://github.com/ABAPlan/frontend-reader.git
        BACKEND_URL: backend.${BASE_URL}
    environment:
      VIRTUAL_HOST: reader.${BASE_URL}
    depends_on:
      - backend-server
  
  wordpress:
    image: wordpress
    environment:
      VIRTUAL_HOST: ${BASE_URL}
      WORDPRESS_DB_HOST: wordpress-database
      WORDPRESS_DB_USER: ${WP_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WP_DB_PASS}
      WORDPRESS_DB_NAME: ${WP_DB_NAME}
    expose:
      - "80"
    depends_on:
      - wordpress-database
  
  reverse-proxy:
    build: ./images/reverse-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - backend-server
      - frontend-editor
      - frontend-reader
      - wordpress
